# fly.toml app configuration file generated for pentacles on 2024-01-12T20:07:16-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pentacles"
primary_region = "sea"

[build]

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
